# Kata Design System - SwiftLint Rules
# Usage: Copy custom_rules section to your project's .swiftlint.yml

identifier_name:
  excluded:
    - xs
    - sm
    - md
    - lg
    - xl
    - x
    - y
    - a
    - r
    - g
    - b
    - s
    - t
    - c

custom_rules:
  kata_no_hardcoded_color:
    name: "Use Kata Color Tokens"
    regex: '\.(foregroundColor|foregroundStyle)\s*\(\s*\.(red|blue|green|yellow|white|black|gray|orange|purple|pink|cyan|mint|teal|indigo|brown|primary|secondary|accentColor)'
    message: "Use Kata color tokens: .foreground(\\.primary)"
    severity: warning

  kata_no_color_init:
    name: "Avoid Color Initializers"
    regex: 'Color\s*\(\s*(red|uiColor|nsColor|hue|white|black):'
    message: "Use Kata color tokens instead of Color initializers"
    severity: warning

  kata_no_hardcoded_font:
    name: "Use Kata Typography Tokens"
    regex: '\.font\s*\(\s*\.(system|custom)\s*\('
    message: "Use Kata typography: .textStyle(\\.body)"
    severity: warning

  kata_no_hardcoded_font_size:
    name: "Use Kata Typography Tokens"
    regex: '\.font\s*\(\s*\.system\s*\(\s*size:'
    message: "Use Kata typography: .textStyle(\\.body)"
    severity: warning

  kata_no_hardcoded_padding:
    name: "Use Kata Spacing Tokens"
    regex: '\.padding\s*\(\s*\d+\.?\d*\s*\)'
    message: "Use Kata spacing: .padding(\\.md)"
    severity: warning

  kata_no_hardcoded_padding_edges:
    name: "Use Kata Spacing Tokens"
    regex: '\.padding\s*\(\s*\.(all|horizontal|vertical|top|bottom|leading|trailing)\s*,\s*\d+\.?\d*\s*\)'
    message: "Use Kata spacing: .padding(\\.md, edges: .horizontal)"
    severity: warning

  kata_no_hardcoded_radius:
    name: "Use Kata Radius Tokens"
    regex: '\.cornerRadius\s*\(\s*\d+\.?\d*\s*\)'
    message: "Use Kata radius: .cornerRadius(\\.md)"
    severity: warning

  kata_no_hardcoded_frame_spacing:
    name: "Use Kata Spacing Tokens"
    regex: '(VStack|HStack|LazyVStack|LazyHStack)\s*\(\s*spacing\s*:\s*\d+\.?\d*\s*\)'
    message: "Consider using Kata spacing tokens for consistency"
    severity: warning

excluded:
  - .build
  - DemoApp/.build
  - Package.swift
  - DemoApp/Package.swift
  - Sources/Kata/Defaults/Theme+Standard.swift
