identifier_name:
  excluded:
    - xs
    - sm
    - md
    - lg
    - xl
    - x
    - y
    - a
    - r
    - g
    - b

custom_rules:
  kata_no_hardcoded_padding:
    name: "Use Kata Spacing Tokens"
    regex: '\.padding\s*\(\s*\d+\.?\d*\s*\)'
    message: "Use Kata spacing: .padding(\\.md)"
    severity: warning

  kata_no_hardcoded_padding_edges:
    name: "Use Kata Spacing Tokens"
    regex: '\.padding\s*\(\s*\.(all|horizontal|vertical|top|bottom|leading|trailing)\s*,\s*\d+\.?\d*\s*\)'
    message: "Use Kata spacing: .padding(\\.md, edges: .horizontal)"
    severity: warning

  kata_no_hardcoded_radius:
    name: "Use Kata Radius Tokens"
    regex: '\.cornerRadius\s*\(\s*\d+\.?\d*\s*\)'
    message: "Use Kata radius: .cornerRadius(\\.md)"
    severity: warning

  kata_no_hardcoded_frame_spacing:
    name: "Use Kata Spacing Tokens"
    regex: '(VStack|HStack|LazyVStack|LazyHStack)\s*\(\s*spacing\s*:\s*\d+\.?\d*\s*\)'
    message: "Consider using Kata spacing tokens for consistency"
    severity: warning

excluded:
  - .build
  - DemoApp/.build
  - Package.swift
  - DemoApp/Package.swift
  - Sources/Kata/Defaults/Theme+Standard.swift
